# -*- coding: utf-8 -*-
"""NIDS_DM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xct3oksZxKzK1cNMgQRlVa9DboKZXJT2

# Machine Learning–Based Network Intrusion Detection System (NIDS)

**Course:** Introduction to Data Mining  
**Student:** Md Shariful Islam  
**UNBC ID:** 230168914  

This notebook follows the project proposal:

- Use CIC-IDS-2017 (multiple days/files) to build a Network Intrusion Detection System
- Apply data cleaning, EDA, feature selection (RFE, tree-based importance)
- Train multiple ML models (LR, KNN, DT, RF, XGBoost, LightGBM, AdaBoost, CatBoost, Voting)
- Evaluate using Accuracy, Precision, Recall, F1-score, and confusion matrices
- Compare single vs ensemble models and analyze important features.

## 1. Imports & Initialization
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier,
    VotingClassifier,
)
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
# Optional gradient boosting libraries
try:
    from xgboost import XGBClassifier
except ImportError:
    XGBClassifier = None

try:
    from catboost import CatBoostClassifier
except ImportError:
    CatBoostClassifier = None

sns.set(style="whitegrid")

"""## 2. Load & Merge CIC-IDS-2017 CSV Files

For simplicity, I am considering only 4 file of CIC-IDS-2017 CSVs.

Suggested files:
- `Monday-WorkingHours.pcap_ISCX.csv` (mostly BENIGN)
- `Wednesday-workingHours.pcap_ISCX.csv` (mixed)
- `Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv`
- `Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv`
"""

# TODO: adjust these paths to your local data directory
print("For best learning at 4 files are required")
files = [
    "../data/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
]
files

def load_cic_file(path: str) -> pd.DataFrame:
    """Load a CIC-IDS-2017 CSV and normalize column names."""
    df = pd.read_csv(path)
    # strip spaces from column names
    df.columns = df.columns.str.strip()
    return df

dfs = []
for f in files:
    print("Loading:", f)
    df_tmp = load_cic_file(f)
    print("  Shape:", df_tmp.shape)
    dfs.append(df_tmp)

len(dfs)

"""### 2.1 Align columns and concatenate

Keeping the columns that are common across all selected files (including `Label`).
"""

# Find common columns across all dataframes
common_cols = set(dfs[0].columns)
for d in dfs[1:]:
    common_cols = common_cols.intersection(set(d.columns))

common_cols = sorted(list(common_cols))
print("Number of common columns:", len(common_cols))
print("Sample common columns:", common_cols[:20])

# Keep only common columns and concatenate
dfs_common = [d[common_cols].copy() for d in dfs]
df_full = pd.concat(dfs_common, axis=0, ignore_index=True)
print("Merged shape:", df_full.shape)
df_full.head()

"""## 3. Data Cleaning & Label Normalization
For hardware limitation and faster processing, I am taking 10% of the total imported records to run my experient.
As per the proposal:
- Remove NaNs, infinities, and duplicates
- Normalize the label into a binary target: BENIGN vs ATTACK.
"""

df = df_full.copy()

# replace infinities with NaN
df = df.replace([np.inf, -np.inf], np.nan)

# drop rows with NaN values
df = df.dropna()

# drop duplicate rows
df = df.drop_duplicates()

print("Total records:", df.shape)

# taking 10% of the total rows
df=df.sample(frac=0.10, random_state=52)

print("After cleaning (10% of the imported records):", df.shape)
df.head()

# inspect label values
df['Label'] = df['Label'].astype(str).str.strip()
df['Label'].value_counts()

# map to binary: 0 = BENIGN, 1 = any ATTACK
def map_binary(label: str) -> int:
    label = str(label).upper()
    if "BENIGN" in label:
        return 0
    else:
        return 1

df['Attack_Binary'] = df['Label'].apply(map_binary)
df['Attack_Binary'].value_counts()

"""## 4. Exploratory Data Analysis (EDA)

- Class distribution
- Summary statistics
- Correlation heatmap (for a subset of features).
"""

# Class distribution
plt.figure(figsize=(5, 4))
sns.countplot(x='Attack_Binary', data=df)
plt.xticks([0, 1], ['BENIGN', 'ATTACK'])
plt.title('Class Distribution: BENIGN vs ATTACK')
plt.tight_layout()
plt.show()

# Basic numeric summary
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
df[numeric_cols].describe().T.head(20)

# Correlation heatmap on a subset of features (to keep it readable)
corr_cols = [c for c in numeric_cols if c != 'Attack_Binary']

# If there are many features, sample a subset for visualization
max_corr_features = 70
corr_sample_cols = corr_cols[:max_corr_features]

corr = df[corr_sample_cols].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(corr, cmap='coolwarm', square=False, cbar=True)
plt.title('Feature Correlation Heatmap (subset)')
plt.tight_layout()
plt.show()

# Keep only upper triangle of the correlation matrix
upper = np.triu(np.ones(corr.shape), k=1).astype(bool)
upper_corr = corr.where(upper)

# Threshold for "too highly correlated"
threshold = 0.90

# Find columns to drop
to_drop = [
    column for column in corr.columns
    if any(upper_corr[column] > threshold)
]

print("Highly correlated features to drop (>", threshold, "):")
for col in to_drop:
    print("-", col)

# Drop redundant features
df_filtered = df.drop(columns=to_drop)
filtered_feature_cols = [c for c in df_filtered.columns if c != 'la']

print("\nNumber of original features:", len(corr_sample_cols))
print("Number of features after correlation filter:", len(filtered_feature_cols))

"""## 5. Feature Selection & Train/Test Split

Based on the proposal:
- Use numeric features as input (excluding the binary label)
- Split into train/test sets
- Standardize features
- Apply RFE with RandomForest to select top features.
"""

# Define input features and target

filtered_feature_cols = [
    c for c in filtered_feature_cols
    if c not in ['Label', 'Attack_Binary']
]

#print (filtered_feature_cols)
print ("Number of filtered features: ", len(filtered_feature_cols))

X = df[filtered_feature_cols].values
y = df['Attack_Binary'].values

# Train/test split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled.shape, X_test_scaled.shape

from sklearn.feature_selection import RFE

rf_for_rfe = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rfe = RFE(estimator=rf_for_rfe, n_features_to_select=20, step=1)

rfe.fit(X_train_scaled, y_train)

selected_mask = rfe.support_
selected_features = [f for f, m in zip(filtered_feature_cols, selected_mask) if m]

print("Selected features (RFE, top 20):")
for f in selected_features:
    print("-", f)

X_train_sel = X_train_scaled[:, selected_mask]
X_test_sel = X_test_scaled[:, selected_mask]
X_train_sel.shape, X_test_sel.shape

"""## 6. Model Implementation & Evaluation

Now trainining with multiple models:

- Logistic Regression  
- K-Nearest Neighbors
- Support Vector Machine
- Naive Bayes
- Decision Tree  
- Random Forest  
- Gradient Boosting  
- XGBoost
- AdaBoost  
- CatBoost  

Now, I will compare performance metrics and confusion matrices.
"""

models = {}

# Classical ML
models["LogisticRegression"] = LogisticRegression(max_iter=1000, n_jobs=-1)
models["KNN"] = KNeighborsClassifier(n_neighbors=5)
models["SVM_RBF"] = SVC(kernel="rbf", probability=False, random_state=42)
models["NaiveBayes"] = GaussianNB()
models["DecisionTree"] = DecisionTreeClassifier(random_state=42)

# Ensemble tree models
models["RandomForest"] = RandomForestClassifier(
    n_estimators=200, random_state=42, n_jobs=-1
)
models["GradientBoosting"] = GradientBoostingClassifier(random_state=42)
models["AdaBoost"] = AdaBoostClassifier(random_state=42)

# Try importing XGBoost
try:
    from xgboost import XGBClassifier
    models["XGBoost"] = XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric='logloss',
        random_state=42
    )
except ImportError:
    print("XGBoost not installed, skipping...")



# Try importing CatBoost
try:
    from catboost import CatBoostClassifier
    models["CatBoost"] = CatBoostClassifier(
        iterations=300,
        depth=6,
        learning_rate=0.1,
        verbose=0,
        random_state=42
    )
except ImportError:
    print("CatBoost not installed, skipping...")

models

results = {}

for name, model in models.items():
    print(f"\n=== Training {name} ===")
    model.fit(X_train_sel, y_train)
    y_pred = model.predict(X_test_sel)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average="weighted", zero_division=0)
    rec = recall_score(y_test, y_pred, average="weighted", zero_division=0)
    f1 = f1_score(y_test, y_pred, average="weighted", zero_division=0)

    print(classification_report(y_test, y_pred, target_names=["BENIGN", "ATTACK"], digits=5))

    results[name] = {
        "Accuracy (%)": acc * 100,
        "Precision (%)": prec * 100,
        "Recall (%)": rec * 100,
        "F1-Score (%)": f1 * 100
    }

results_df = pd.DataFrame(results).T.reset_index().rename(columns={"index": "Model"})
results_df = results_df.sort_values(by="Accuracy (%)", ascending=False)

print("\n=== Model Comparison (Test Set) ===")
results_df



# Use your results_df directly
plt.figure(figsize=(8,4))
plt.bar(results_df["Model"], results_df["Accuracy (%)"])

plt.title("Model Accuracy (Test Set)")
plt.xlabel("Model")
plt.ylabel("Accuracy (%)")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

#group bar chart


# Metric names
metrics = ["Accuracy (%)", "Precision (%)"]

# Number of models

num_models = len(results_df["Model"])

# X positions for each model
x = np.arange(num_models)

# Width of each bar in the group
bar_width = 0.2

# Plot each metric shifted on x-axis
plt.figure(figsize=(10, 5))

plt.bar(x - 1.5*bar_width, results_df["Accuracy (%)"],  width=bar_width, label="Accuracy")
plt.bar(x - 0.5*bar_width, results_df["Precision (%)"], width=bar_width, label="Precision")
#plt.bar(x + 0.5*bar_width, results_df["Recall (%)"],    width=bar_width, label="Recall")
#plt.bar(x + 1.5*bar_width, results_df["F1-Score (%)"],  width=bar_width, label="F1-Score")

# Title and labels
plt.title("Model Comparison Metrics (Test Set)")
plt.xlabel("Model")
plt.ylabel("Score (%)")

# X-axis
plt.xticks(x, models, rotation=45)

# Show legend
plt.legend()

plt.tight_layout()
plt.show()

"""## 8 Feature Importance"""

# Use the fitted RandomForest model
rf_final = models["RandomForest"]
importances = rf_final.feature_importances_

fi_df = pd.DataFrame({
    "Feature": selected_features,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

print("=== Feature Importance (RandomForest on RFE-selected features) ===")
fi_df

plt.figure(figsize=(10, 6))
plt.barh(fi_df["Feature"], fi_df["Importance"])
plt.gca().invert_yaxis()  # highest importance at top
plt.xlabel("Importance")
plt.title("Feature Importance (RandomForest, RFE-selected features)")
plt.tight_layout()
plt.show()

"""## 10 Sample Testing"""
print ("Testing random sample using RandomForest")
# Sample one random row from the filtered dataframe
sample = df.sample(1, random_state=99)
sample_features = sample[filtered_feature_cols]

# Scale using the same scaler (remove feature-name warning)
sample_scaled = scaler.transform(sample_features.values)

# Apply RFE mask
sample_selected = sample_scaled[:, selected_mask]

# Get trained RandomForest from the models dict
rf_final = models["RandomForest"]

# Predict with RandomForest
pred = rf_final.predict(sample_selected)[0]
actual = sample["Attack_Binary"].iloc[0]

print("=== Random Flow Prediction Demo (RandomForest) ===")
print("Actual Label   :", "ATTACK" if actual == 1 else "BENIGN")
print("Predicted Label:", "ATTACK" if pred == 1 else "BENIGN")
print("End of the project")


"""## Summary & Discussion
- Dataset description (CIC-IDS-2017 subsets merged: Monday, Wednesday, Friday PortScan, Friday DDoS)
- Preprocessing steps: cleaning, NaN handling, binary label mapping, scaling
- Feature selection: RFE + tree-based importance
- Model comparison: single models vs ensembles (VotingClassifier)
- Trade-offs: accuracy vs computational complexity (e.g., RF/XGBoost vs Logistic Regression)
- Key features driving performance (e.g., bytes/s, packets/s, IAT, flow duration)
"""



